apiVersion: v1
kind: Pod
metadata:
  name: curl-test
spec:
  containers:
  - name: curl
    image: curlimages/curl:latest  # Image with curl installed
    command: ["sleep", "3600"]      # Keep the pod running for an hour

