apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      initContainers:
      - name: wait-for-mysql
        image: curlimages/curl:latest  # Image with curl
        command: ['sh', '-c']
        args:
          - |
            echo "Waiting for MySQL to be ready..."
            until nc -z mysql 3306; do
              echo "MySQL is not yet ready..."
              sleep 2
            done
            echo "MySQL is up - proceeding..."
      containers:
      - name: django
        image: dineshbodala/django-todo-mysql:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "mysql"  # Name of the MySQL service
        - name: DB_NAME
          value: "todo"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "Dinesh123@"
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]



---
apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001  # Optional: specify a port or let Kubernetes assign one
  selector:
    app: django

