apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: dineshbodala/django-todo-mysql:v2
        imagePullPolicy: Always  # <-- Add the imagePullPolicy here
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_NAME
          value: "todo"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "Dinesh123@"
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]


---
apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000  # Optional: specify a port or let Kubernetes assign one
  selector:
    app: django

